### ISSUE TITLE
Serve the issue template outside of GitHub

### ISSUE THREAD

**Issue by mihneadb** [ovidiuch/github-issue-template#9]
GitHub made some changes in the way they serve content from `raw.github...` and this makes Chrome forbid loading of the template data.

A possible way for solving this would be to serve the issue template from a server (so not from GitHub).
- the server would need to allow CORS (guides [here](http://enable-cors.org/server.html))
- we'd like a magic workflow of keeping things in sync, so that would require a github [hook](https://developer.github.com/webhooks/) that triggers an update on the server

**Comment by mihneadb** [comment]
-- I didn't use the issue template because it was not working :P.

**Comment by ovidiuch** [comment]
Couldn't we just use CORS as a proxy and serve the file directly from rawgithub.com? (e.g. https://rawgit.com/skidding/github-issue-template/master/template.md)

**Comment by mihneadb** [comment]
Oh right, that's even better!

On Tue, Apr 29, 2014 at 5:11 PM, Ovidiu Cherecheș
notifications@github.comwrote:

> Couldn't we just use CORS as a proxy and serve the file directly from
> rawgithub.com? (e.g.
> https://rawgit.com/skidding/github-issue-template/master/template.md)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/skidding/github-issue-template/issues/9#issuecomment-41688656
> .

## 

Mihnea Dobrescu-Balaur

**Comment by mihneadb** [comment]
It looks like we only need to run https://pypi.python.org/pypi/corsa/0.1.2 on a server and change the github extension to get the md from `SERVER/proxy/https://rawgit.com/skidding/github-issue-template/master/template.md`.

**Comment by mihneadb** [comment]
Testing it locally now. Need

```
corsa --allow-proxy http://rawgit.com --allow-origin ALL
```

**Comment by mihneadb** [comment]
Ok, it's working. We get a warning that we are proxying through http and not https, but.. that's a different problem.
